overblog_graphql:
    definitions:
        schema:
            public:
                query: Public
        mappings:
            types:
                -
                    type: yaml
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: ~
