security:
    access_decision_manager:
      strategy: unanimous

    encoders:
        App\Entity\User:
          algorithm: bcrypt
        App\Entity\Staff:
          algorithm: sha256

    providers:
        user:
          entity:
            class: App\Entity\BaseUser

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
          anonymous: ~
          logout: ~

          guard:
            authenticators:
              - App\Security\UserTokenAuthenticator
