security:
    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    encoders:
        App\Entity\User:
          algorithm: bcrypt
        App\Entity\Staff:
          algorithm: sha256
        Symfony\Component\Security\Core\User\User:
          algorithm: 'auto'

    providers:
        users_in_memory: { memory: null }
        user_provider:
          entity:
            class: App\Entity\BaseUser

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/*$
            anonymous: true
            lazy: true
            provider: user_provider
            guard:
              authenticators:
                - App\Utils\Authentication\UserTokenAuthenticator

    access_control:
         #- { path: ^/profile, roles: ROLE_CLIENT }
         #- { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
