http:
  address: "0.0.0.0:80"
  uploads:
    forbid: [".php", ".exe", ".bat"]
  workers:
    command: "php bin/console baldinof:roadrunner:worker"
    relay: "unix://var/roadrunner.sock"

limit:
  interval: 1
  services:
    http:
      maxMemory: 64
      TTL: 0
      idleTTL: 0
      execTTL: 60

static:
  enable: true
  dir:   "public"
  forbid: [".php", ".htaccess"]
