http:
  address: 0.0.0.0:8080
  uploads:
    forbid: [".php", ".exe", ".bat"]
  workers:
    numWorkers: 4
    command: "php bin/console baldinof:roadrunner:worker"
    relay: "unix://var/roadrunner.sock"

limit:
  interval: 1
  services:
    http:
      maxMemory: 64
      TTL: 0
      idleTTL: 0
      execTTL: 60

static:
  enable: false
  dir: "public"
  forbid: [".php", ".htaccess"]

reload:
  enabled: true
  interval: 1s
  patterns: [ ".php" ]
  services:
    http:
      recursive: true
      ignore: [ "vendor" ]
      patterns: [ ".php", ".go",".md", ]
      dirs: [ "." ]