version: '3.5'

services:
    service:
        build: '.'
        environment:
            APP_ENV: 'dev'
            APP_DEBUG: 'true'
            DATABASE_URL: 'mysql://dev:dev@mysql:3306/dev'
            #VIRTUAL_HOST: dev.lacker
            PHP_IDE_CONFIG: 'serverName=dev.lacker.docker'
            APP_TYPE: 'dev'
        #command: tail -f /dev/null

        volumes:
            - ".:/server"
            - "./.docker/etc/php/php-dev.ini:/etc/php/7.4/fpm/conf.d/60-dev.ini"
            - "./.docker/etc/php/php-cli.ini:/etc/php/7.4/cli/conf.d/60-dev.ini"
            - './.rr.yaml:/etc/roadrunner/.rr.yaml'
        depends_on:
            - mysql
        networks:
            - dev-back
        ports:
            - "80:80"
    mysql:
        image: mysql:5.7
        restart: unless-stopped
        ports:
            - "3306:3306"
        networks:
            - dev-back
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dev
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev
            VIRTUAL_HOST: mysql.dev.lacker
        volumes:
            - mysql-data:/var/lib/mysql


volumes:
    mysql-data:
        name: dev_mysql_data

networks:
    dev-back:
        driver: bridge
