version: '3.5'

volumes:
  mysql-data:
    name: dev_mysql_data
  nginx_certs:
  nginx_vhosts:
  nginx_html:

networks:
  dev-back:
    driver: bridge

services:
  app: &app
    build: '.'
    container_name: lacker.app
    command: echo "service app disabled"
    environment:
      APP_ENV: 'dev'
      APP_DEBUG: 'true'
      DATABASE_URL: $DATABASE_URL
      APP_TYPE: 'dev'
    volumes:
     - ./src:/app/
     - /app/bin
    depends_on:
        mysql:
          condition: service_healthy
    networks:
      - dev-back

  proxy:
    container_name: proxy
    image: jwilder/nginx-proxy:alpine
    environment:
      DHPARAM_GENERATION: "false"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_certs:/etc/nginx/certs:ro
      - nginx_vhosts:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    networks:
      - dev-back
    depends_on:
      - web.app
    restart: always

  certificate:
    container_name: cert
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      DEFAULT_EMAIL: $COMPANY_EMAIL
      NGINX_PROXY_CONTAINER: proxy
      NGINX_DOCKER_GEN_CONTAINER: proxy
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_certs:/etc/nginx/certs:rw
      - nginx_html:/usr/share/nginx/html
    restart: always
    networks:
      - dev-back

  web.app:
    <<: *app
    command: /app/bin/rr serve -c /app/.rr.yaml
    container_name: lacker.web
    environment:
      VIRTUAL_HOST: $VIRTUAL_HOST
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: $VIRTUAL_HOST

  mysql:
    container_name: lacker.db
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      - dev-back
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10