version: '3.5'

services:
    service:
        build: '.'
        environment:
            APP_ENV: 'dev'
            APP_DEBUG: 'true'
            VIRTUAL_HOST: $VIRTUAL_HOST
            DATABASE_URL: $DATABASE_URL
            LETSENCRYPT_HOST: $VIRTUAL_HOST
            PHP_IDE_CONFIG: 'serverName=dev.lacker.docker'
            APP_TYPE: 'dev'
        ports:
          - "80:80"
          - "443:443"
        volumes:
#            - .:/server
            - ./.docker/etc/php/php-dev.ini:/etc/php/7.4/fpm/conf.d/60-dev.ini
            - ./.docker/etc/php/php-cli.ini:/etc/php/7.4/cli/conf.d/60-dev.ini
            - ./.rr.yaml:/etc/roadrunner/.rr.yaml
        depends_on:
            - mysql
        networks:
            - dev-back

    mysql:
        image: mysql:5.7
        restart: unless-stopped
#        ports:
#            - "3306:3306"
        networks:
            - dev-back
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
        volumes:
            - mysql-data:/var/lib/mysql


volumes:
  mysql-data:
        name: dev_mysql_data
  nginx_html:
  nginx_vhost:
  nginx_conf:
  certificates:

networks:
    dev-back:
        driver: bridge