overblog_public_graphql_endpoint:
    path: /{schemaName}
    defaults:
        _controller: Overblog\GraphQLBundle\Controller\GraphController::endpointAction
        _format: "json"
    requirements:
        schemaName: 'public|private|profile'

