Menu:
  type: object
  config:
    resolveField: '@=resolver("App\\GraphQL\\Resolver\\MenuResolver",[info, value, args])'
    fields:
      id:
        type: ID!
      name:
        type: String!
      dishes:
        type: '[Dish]'