Portion:
  type: object
  config:
    resolveField: '@=resolver("App\\GraphQL\\Resolver\\PortionResolver",[info, value, args])'
    fields:
      id:
        type: String!
      size:
        type: String!
      price:
        type: String!