Query:
  type: object
  config:
    fields:
      Portion:
        type: Portion
        args: {id: {type: Int}}
        resolve: '@=resolver("App\\GraphQL\\Resolver\\PortionResolver::resolve", [args["id"]])'
      Dish:
        type: Dish
        args: { id: { type: Int } }
        resolve: '@=resolver("App\\GraphQL\\Resolver\\DishResolver::resolve", [args["id"]])'
      Restaurant:
        type: Restaurant
        args: { id: { type: Int } }
        resolve: '@=resolver("App\\GraphQL\\Resolver\\RestaurantResolver::resolve", [args["id"]])'
      Business:
        type: Business
        args: { id: { type: Int } }
        resolve: '@=resolver("App\\GraphQL\\Resolver\\BusinessResolver::resolve", [args["id"]])'
      Staff:
        type: Staff
        args: { id: { type: Int } }
        resolve: '@=resolver("App\\GraphQL\\Resolver\\StaffResolver::resolve", [args["id"]])'
      Menu:
        type: Menu
        args: { id: { type: Int } }
        resolve: '@=resolver("App\\GraphQL\\Resolver\\MenuResolver::resolve", [args["id"]])'

