Staff:
  type: object
  config:
    resolveField: '@=resolver("App\\GraphQL\\Resolver\\StaffResolver",[info, value, args])'
    fields:
      id: {type: ID!}
      email: {type: String!}
      name: {type: String!}
      business: {type: Business!}
      restaurants: {type: '[Restaurant]'}
      roles: {type: '[String]'}