# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Types/Image.php'
            - '../src/Types/Lang.php'
            - '../src/Types/Price.php'
            - '../src/Security/JWTObject.php'
            - '../src/Security/JWTObjectSigner.php'
            - '../src/Configurators/ClosureMethodCollection.php'
            - '../src/Configurators/ReflectionPropertyCollection.php'
            - '../src/Configurators/ReflectionReferenceCollection.php'
            - '../src/Configurators/Exception/'
            - '../src/Configurators/Attributes/'
            - '../src/Api/ApiEntity.php'
            - '../src/Api/ApiEntityCollection.php'
            - '../src/Api/Attributes/'
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Api\Normalizer\DatetimeNormalizer:
      public: true
      lazy: true

    App\Api\Normalizer\LangNormalizer:
      public: true
      lazy: true

    App\Api\Normalizer\UuidNormalizer:
      public: true
      lazy: true

    app.config.restaurant:
        lazy: true
        public: true
        class: App\Configurators\Entity\RestaurantConfig
    app.config.dish:
        public: true
        lazy: true
        class: App\Configurators\Entity\DishConfig
    app.config.staff:
        public: true
        lazy: true
        class: App\Configurators\Entity\StaffConfig
    app.config.table:
      public: true
      lazy: true
      class: App\Configurators\Entity\TableConfig
    app.config.user:
      public: true
      lazy: true
      class: App\Configurators\Entity\UserConfig
    app.config.order:
      public: true
      lazy: true
      class: App\Configurators\Entity\OrderConfig
    app.config.menu:
      public: true
      lazy: true
      class: App\Configurators\Entity\MenuConfig
    app.config.portion:
      public: true
      lazy: true
      class: App\Configurators\Entity\PortionConfig
    app.config.suborder:
      public: true
      lazy: true
      class: App\Configurators\Entity\SubOrderConfigurator
    app.config.appeal:
      public: true
      lazy: true
      class: App\Configurators\Entity\AppealConfiguration
    Google_Client:
        class: Google_Client
        calls:
            - [ setClientId, [ '%env(GOOGLE_CLIENT_ID)%' ] ]
            - [ setClientSecret, [ '%env(GOOGLE_CLIENT_SECRET)%' ] ]
    App\Events\PasswordEncoderListener:
        tags:
          - { name: 'doctrine.event_subscriber', connection: 'default' }
    App\Events\SuborderListener:
      tags:
        - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\SubOrder' }
        - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\SubOrder' }
    App\Events\PortionListener:
        tags:
          - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Portion' }
          - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Portion' }
    App\Events\DishEventListener:
      tags:
        - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Dish' }
        - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Dish' }
    App\Events\MenuEventListener:
      tags:
        - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Menu' }
        - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Menu' }