# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
    app.config.restaurant:
        public: true
        class: App\Configurators\Entity\RestaurantConfigurator
    app.config.dish:
        public: true
        class: App\Configurators\Entity\DishConfigurator
    app.config.portion:
        public: true
        class: App\Configurators\Entity\PortionConfigurator
    Google_Client:
        class: Google_Client
        calls:
            - [ setDeveloperKey, [ '%env(GOOGLE_API_KEY)%' ] ]
            - [ setClientId, [ '%env(GOOGLE_CLIENT_ID)%' ] ]
            - [ setClientSecret, [ '%env(GOOGLE_CLIENT_SECRET)%' ] ]